name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy to azure
        uses: azure/appservice-actions/webapp@master
        with:
          app-name: bsdetector
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
